name: flutter_libmad
description: A Flutter plugin providing bindings to the libmad library through Dart FFI, enabling high-quality MP3 decoding in your Flutter applications.
version: 0.0.1
homepage: https://grevity.in

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  ffi: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.gurkaran.flutter_libmad.flutter_libmad
        pluginClass: FlutterLibmadPlugin
      ios:
        pluginClass: FlutterLibmadPlugin